var foo = new ArrayBuffer(4);
var bar;
foo[0] = 0;
foo[1] = 1;
foo[2] = 2;
foo[3] = 3;
bar = foo.slice(0);
bar[0]=12;
console.log(foo);
console.log(bar);
console.log(foo.slice(2, 4));
console.log(foo.slice(2, foo.byteLength));
console.log(foo.slice(2));
console.log(foo.slice(-2));